server:
  port: 8080

spring:
  application:
    name: HR_management
  config:
    import: "application-secret.yaml"
  flyway:
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  docker:
    compose:
      enabled: false

  web:
    resources:
      static-locations: E:\\Java\\HR_management\\images

  cache:
    type: redis

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    enabled: true
    path: swagger-uix.html
  api-docs:
    path: /v3/api-docs

form-fields-url:
  name: https://drive.google.com/uc?id=1kIVhDGE8Gs3pjSfzUZDIYOdZl-kTURwM


